display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        user_bulk_form:
          label: 'Mise à jour en masse'
        name:
          label: 'Nom d''utilisateur'
        status:
          label: État
          settings:
            format_custom_true: Actif
        roles_target_id:
          label: Rôles
        operations:
          label: Actions
      filters:
        status:
          group_info:
            label: État
            group_items:
              1:
                title: Actif
