display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        tmgmt_local_task_bulk_form:
          label: 'Mise à jour en masse'
          action_title: 'Pour la sélection'
        title:
          label: Titre
        word_count:
          label: Mots
        item_count:
          label: Éléments
        progress:
          label: Progression
      title: 'Tâches Locales'
  assigned:
    display_title: Attribué
    display_options:
      menu:
        title: Attribué
      fields:
        tmgmt_local_task_bulk_form:
          label: 'Mise à jour en masse'
          action_title: 'Pour la sélection'
        status:
          label: État
        progress:
          label: Progression
        tuid:
          label: Cessionnaire
        title:
          label: Titre
        source_language:
          label: 'A partir de'
        target_language:
          label: À
        word_count:
          label: Mots
        item_count:
          label: Éléments
        loop_count:
          label: Boucles
        operations:
          label: Actions
      filters:
        source_language:
          expose:
            label: 'Langue d''origine'
        uid:
          expose:
            label: Fournisseur
        title:
          expose:
            label: Titre
  closed:
    display_title: Fermé
    display_options:
      menu:
        title: Fermé
      fields:
        tmgmt_local_task_bulk_form:
          label: 'Mise à jour en masse'
          action_title: 'Pour la sélection'
        status:
          label: État
        progress:
          label: Progression
        created:
          label: Créé
        tuid:
          label: Cessionnaire
        title:
          label: Titre
        source_language:
          label: 'A partir de'
        target_language:
          label: À
        word_count:
          label: Mots
        item_count:
          label: Éléments
        loop_count:
          label: Boucles
        operations:
          label: Actions
      filters:
        source_language:
          expose:
            label: 'Langue d''origine'
        uid:
          expose:
            label: Fournisseur
        title:
          expose:
            label: Titre
  completed:
    display_title: Terminé
    display_options:
      menu:
        title: Terminé
      fields:
        tmgmt_local_task_bulk_form:
          label: 'Mise à jour en masse'
          action_title: 'Pour la sélection'
        status:
          label: État
        progress:
          label: Progression
        created:
          label: Créé
        tuid:
          label: Cessionnaire
        title:
          label: Titre
        source_language:
          label: 'A partir de'
        target_language:
          label: À
        word_count:
          label: Mots
        item_count:
          label: Éléments
        loop_count:
          label: Boucles
        operations:
          label: Actions
      filters:
        source_language:
          expose:
            label: 'Langue d''origine'
        uid:
          expose:
            label: Fournisseur
        title:
          expose:
            label: Titre
  pending:
    display_title: 'En attente'
    display_options:
      menu:
        title: 'En attente'
      fields:
        tmgmt_local_task_bulk_form:
          label: 'Mise à jour en masse'
          action_title: 'Pour la sélection'
        status:
          label: État
        tuid:
          label: Cessionnaire
        title:
          label: Titre
        progress:
          label: Progression
        source_language:
          label: 'A partir de'
        target_language:
          label: À
        word_count:
          label: Mots
        item_count:
          label: Éléments
        loop_count:
          label: Boucles
        operations:
          label: Actions
      filters:
        source_language:
          expose:
            label: 'Langue d''origine'
        uid:
          expose:
            label: Fournisseur
        title:
          expose:
            label: Titre
  rejected:
    display_title: Rejeté
    display_options:
      menu:
        title: Rejeté
      fields:
        tmgmt_local_task_bulk_form:
          label: 'Mise à jour en masse'
          action_title: 'Pour la sélection'
        status:
          label: État
        progress:
          label: Progression
        created:
          label: Créé
        tuid:
          label: Cessionnaire
        title:
          label: Titre
        source_language:
          label: 'A partir de'
        target_language:
          label: À
        word_count:
          label: Mots
        item_count:
          label: Éléments
        loop_count:
          label: Boucles
        operations:
          label: Actions
      filters:
        source_language:
          expose:
            label: 'Langue d''origine'
        uid:
          expose:
            label: Fournisseur
        title:
          expose:
            label: Titre
  unassigned:
    display_options:
      fields:
        tmgmt_local_task_bulk_form:
          label: 'Mise à jour en masse'
          action_title: 'Pour la sélection'
        status:
          label: État
        title:
          label: Titre
        source_language:
          label: 'A partir de'
        target_language:
          label: À
        word_count:
          label: Mots
        item_count:
          label: Éléments
        loop_count:
          label: Boucles
        operations:
          label: Actions
