label: Commentaires
display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          tags:
            previous: "‹\_précédent"
            next: "suivant\_›"
            first: "«\_premier"
            last: "dernier\_»"
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        comment_bulk_form:
          action_title: Action
        subject:
          label: Objet
        operations:
          label: Actions
      filters:
        subject:
          expose:
            label: Objet
        langcode:
          expose:
            label: Langue
      title: Commentaires
  page_published:
    display_options:
      menu:
        title: Commentaires
  page_unapproved:
    display_options:
      filters:
        subject:
          expose:
            label: Objet
        langcode:
          expose:
            label: Langue
      fields:
        comment_bulk_form:
          action_title: Action
        subject:
          label: Objet
        operations:
          label: Actions
