display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
          tags:
            previous: '‹ vorherige Seite'
            next: 'nächste Seite ›'
            first: '« erste Seite'
            last: 'letzte Seite »'
      fields:
        state:
          label: Status
        label:
          label: Beschriftung
        type:
          label: Typ
        progress:
          label: Fortschritt
        word_count:
          label: Wörter
        tags_count:
          label: Tags
        changed:
          label: Geändert
        operations:
          label: Aktionen
      title: Auftragselemente
      arguments:
        tjid:
          exception:
            title: Alle
  checkout:
    display_title: 'Zur Kasse gehen'
    display_options:
      fields:
        label:
          label: Beschriftung
        type:
          label: Typ
        word_count:
          label: Wörter
        changed:
          label: Geändert
  submitted:
    display_title: Gespeichert
