label: Dateien
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ Vorherige Seite'
            next: 'Nächste Seite ›'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      fields:
        filename:
          label: Name
        status:
          label: Status
      filters:
        status:
          expose:
            label: Status
      title: Dateien
  page_1:
    display_options:
      menu:
        title: Dateien
  page_2:
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Vorherige Seite'
            next: 'Nächste Seite ›'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      arguments:
        fid:
          exception:
            title: Alle
