display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ Vorherige Seite'
            next: 'Nächste Seite ›'
            first: '« Anfang'
            last: 'Ende »'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      fields:
        user_bulk_form:
          label: Massenaktualisierung
        status:
          settings:
            format_custom_true: Aktiv
        roles_target_id:
          label: Rollen
        operations:
          label: Aktionen
      filters:
        status:
          group_info:
            group_items:
              1:
                title: Aktiv
  page_1:
    display_title: Seite
